### ISSUE TITLE
Can you give a brief description on how to run the model on new dataset?

### ISSUE THREAD

**Issue by liweitj47** [HKUST-KnowComp/Deepgraphcnn#5]
Can you give a brief description on how to run the model on new dataset? Such as the order of running the scripts, how to build the graph, and so on.

**Comment by penghts** [comment]
First, you need to convert the text to a graph-of-words representation, and follow the node sequence selection, neighborhood assemble and neighborhood normalization steps to subgraphs-of-words.
Second, you need to convert subgraphs-of-words to a 3-dimensional representation.
Third, you can use the deep convolution neural networks to learn different-level of features.
Fourth,  for hierarchical multi-label classification tasks, you can even add recursive regularization of dependencies between labels into the traditional objective function.
